#
#	General site settings 
#

site:
  name:              "PIP Test Site"
  base:              /pip/public_html/                       # url root of site (i.e. what comes after host name for all pages)

#
# Page settings
#

page:
  default:           index
  title_prefix:      "pip | "
  title_default:     "default page title"
  endings:
    - html
    - htm
    - shtml
  layout_default:    default.rhtml

http:
  Server:             pip-server

#
#	Directory locations
#	- should be specified as physical file relative to site.base as set above
#

files:
  pages:                 public_html/pages
  cache:                 public_html/cache
  layouts:               public_html/layouts
  not_found:             public_html/pages/admin/page_not_found.rhtml
  toolbar:               public_html/pages/admin/toolbar.html

#
# URL locations
# - should be specified as url prefixes for page assets etc
#

urls:
  stylesheets:           /pip/public_html/stylesheets
  images:                /pip/public_html/images
  javascripts:           /pip/public_html/javascripts
